# Generated by Django 5.2.6 on 2025-10-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('urgency', models.CharField(choices=[('info', 'Info'), ('urgent', 'Urgent')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
