# Generated by Django 5.2.6 on 2025-10-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_project', '0002_systemnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
