# Generated by Django 5.2.6 on 2025-10-05 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_project', '0004_remove_systemnotification_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemnotification',
            name='read_by',
        ),
        migrations.CreateModel(
            name='NotificationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_project.systemnotification')),
            ],
            options={
                'unique_together': {('notification', 'user_email')},
            },
        ),
    ]
