# Generated by Django 5.2.6 on 2025-10-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_project', '0005_remove_systemnotification_read_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
