# Generated by Django 5.2.6 on 2025-10-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_project', '0006_alter_institution_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='payment_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
